# Generated by Django 3.1 on 2021-11-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Sockets', models.PositiveIntegerField()),
                ('Has_wifi', models.BooleanField(default=False)),
                ('Ip', models.CharField(max_length=50, null=True)),
                ('Connected_In', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.AddField(
            model_name='status_device',
            name='Socket',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status_device',
            name='PowerStrip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_Xterm_Pyserial.powerstrip'),
        ),
    ]
