# Generated by Django 3.1 on 2021-11-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0002_auto_20211122_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerstrip',
            name='Pin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
