# Generated by Django 3.1 on 2021-11-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0003_powerstrip_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_device',
            name='StatusDevice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
