# Generated by Django 3.1 on 2021-11-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0004_auto_20211123_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_normaluser',
            options={'ordering': ('Group',)},
        ),
        migrations.CreateModel(
            name='Group_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_Xterm_Pyserial.status_device')),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_Xterm_Pyserial.group')),
            ],
            options={
                'ordering': ('Group',),
            },
        ),
    ]
