# Generated by Django 3.1 on 2021-11-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0005_auto_20211128_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_device',
            old_name='Device',
            new_name='Status_Device',
        ),
    ]
