# Generated by Django 3.1 on 2021-11-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0006_auto_20211128_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Device',
        ),
    ]
