# Generated by Django 4.0.4 on 2022-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Xterm_Pyserial', '0008_status_device_devicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_device',
            name='User_using',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
